version: "3.3"
services:
  postgres_sdelka:
    image: teemitze/postgres_sdelka
    container_name: postgres_sdelka
    ports:
      - 5432:5432
  es_sdelka:
    image: teemitze/es_sdelka
    container_name: es_sdelka
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper